### ISSUE TITLE
兄弟 你的nvim的lsp 那种圆形高亮是咋设置的

### ISSUE THREAD

**Issue by HUAHUAI23** [ciza99/dotfiles#1]
像这样的

![image](https://user-images.githubusercontent.com/43649186/215052824-cf5ae171-bb94-4cbe-8103-5b24d2bc90df.png)

**Comment by ciza99** [comment]
Thats what I was asking in the lspsaga repo, I didnt find a way to change it. However if you use my config it wont look like this anyway. I changed the highlight colors in the poimanders theme localy (the theme does not support lspsagas new visuals yet), i might submit a pull request if I get it to a good enough state.

Also post questions in english.

**Comment by HUAHUAI23** [comment]
sorry, i thought you are chinese

**Comment by HUAHUAI23** [comment]
> 
Wait for your news of success

**Comment by HUAHUAI23** [comment]
> Thats what I was asking in the lspsaga repo, I didnt find a way to change it. However if you use my config it wont look like this anyway. I changed the highlight colors in the poimanders theme localy (the theme does not support lspsagas new visuals yet), i might submit a pull request if I get it to a good enough state.
> 
> Also post questions in english.

Wait for your news of success

**Comment by ciza99** [comment]
@HUAHUAI23 They updated lspsaga.nvim and the colors follow the theme better, I also submittedd a PR to poimandres.nvim to add some highlights https://github.com/olivercederborg/poimandres.nvim/pull/28.
